### ISSUE TITLE
Please link to https://qiskit.org/ecosystem/ionq/ in GitHub's About section

### ISSUE THREAD

**Issue by Eric-Arellano** [qiskit-community/qiskit-ionq#126]
It is useful to have the link to the project docs on the GitHub home page for this repo.

To fix this, go to the "Code"/home page of the repo. Then click the wheel on the "about" section on the right. Set the website to https://qiskit.org/ecosystem/ionq/.

![Screenshot 2023-05-15 at 9 55 20 AM](https://github.com/Qiskit-Partners/qiskit-aqt-provider/assets/14852634/5085a3cd-e3d8-43e1-996f-be9e3c9d6147)

Thanks!

**Comment by Eric-Arellano** [comment]
Bump @splch

**Comment by Eric-Arellano** [comment]
Thanks! For some reason, the URL isn't clickable. Maybe it doesn't like the `/` at the end? I realize the other projects don't have that.

![Screenshot 2023-05-23 at 12 08 19 PM](https://github.com/Qiskit-Partners/qiskit-ionq/assets/14852634/10b5f9ed-a247-4ff8-be1d-29862ab34ff3)

**Comment by Cynocracy** [comment]
Ah, can try that out. I noticed the same but wasn't sure it was specific to us

**Comment by Cynocracy** [comment]
Yup! Clickable now, that seems to have done the trick :)
