### ISSUE TITLE
Add support for Qiskit v1.0

### ISSUE THREAD

**Issue by kikomiss** [qiskit-community/qiskit-ionq#161]
### What feature would you like to see added? Why is it valuable?
Since Qiskit is planning to release a new version - [1.0](https://www.ibm.com/quantum/blog/qiskit-1-launch) some time in February, 2024 I would like to propose to prepare a version of `qiskit-ionq` that supports the `qiskit>=1.0,<2.0`. 

Additionally, `qiskit-ionq` has a dependency on [qiskit-terra](https://pypi.org/project/qiskit-terra/) which is going to be deprecated and replaced by [qiskit](https://pypi.org/project/qiskit/) once v1.0 is out (as mentioned [here](https://github.com/Qiskit/qiskit/pull/11271)). It's also worth mentioning that the Qiskit v1.0 is not going to be backwards-compatible with `qiskit-terra`, which means, adding support for Qiskit v1.0 could be a breaking change for `qiskit-ionq` users as well.

Qiskit team has put out a pre-release version - [1.0.0b](https://pypi.org/project/qiskit/1.0.0b1/) which could be used to ensure a smooth transition.

### What is the expected behavior, in detail?
 `qiskit-ionq` supports Qiskit v1

**Comment by kielpins-qctrl** [comment]
Installing `qiskit-ionq` in the same environment as `qiskit>=1.0` now destroys the entire environment. I ended up rebuilding my venv from scratch several times before figuring out that `qiskit-ionq` is the culprit. A warning in the docs would be nice, even if Qiskit 1.0 compatibility is not being actioned.

**Comment by splch** [comment]
hi thanks for the issue! we're now supporting qiskit v1 as of `qiskit-ionq==0.5.0`
