### ISSUE TITLE
Set up GitHub Pages and update the About section

### ISSUE THREAD

**Issue by arnaucasau** [qiskit-community/qiskit-ionq#163]
### Instructions 
The project now has the documentation deployed in a branch called [gh-pages](https://github.com/qiskit-community/qiskit-ionq/tree/gh-pages), but we need to set up the repo to use GitHub Pages by following the next 5 steps. Once the GitHub Pages is set up please update the repo's About section to display the new link.

1. Navigate to your site's repository
2. Click `Settings`
3. Go to `Pages`
4. Select `Deploy from a branch`, under the `Source` section on `Build and deployment`
5. Select the `gh-pages` branch and the `/ (root)` folder in the `Branch` section on `Build and deployment`

![GitHubPages-example](https://github.com/Qiskit/ecosystem/assets/47946624/520f4f0c-905a-4a4f-b918-a580a953e80d)

The default URL where you can find your site is https://qiskit-community.github.io/qiskit-ionq

For further information, you can see the [GitHub Pages Quickstart](https://docs.github.com/en/pages/quickstart#creating-your-website) and https://github.com/Qiskit/ecosystem/issues/578.

**Comment by Eric-Arellano** [comment]
Gentle bump on this @Cynocracy - some config you need to set up to finish deploying GitHub pages. We'll set up qiskit.org redirects after.

**Comment by Cynocracy** [comment]
Thanks for the ping!

**Comment by Cynocracy** [comment]
@ColemanCollins are you an admin on the repo at the moment, and can you grant me permissions or help with the changes above?

**Comment by Cynocracy** [comment]
https://qiskit-community.github.io/qiskit-ionq/ live!
